graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: Telenor Agreement Q
  cdn:
    enabled: false
    version: 0.11.11