apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: openshiftfabric8-s2i
  namespace: myproject
spec:
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'openshiftfabric8:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'fabric8/s2i-java:2.3'
    type: Source
  triggers: []
